spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:appuser}
    password: ${SPRING_RABBITMQ_PASSWORD:supersecret123}
app:
  mq:
    queue: ${APP_MQ_QUEUE:docs.uploaded.q}
