spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:paperless}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:paperless}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:paperless}}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
server:
  port: ${SERVER_PORT:${APP_PORT:8080}}

app:
  mq:
    exchange: ${APP_MQ_EXCHANGE:docs.exchange}
    routing: ${APP_MQ_ROUTING:document.uploaded}
    queue: ${APP_MQ_QUEUE:docs.uploaded.q}
    dlx: docs.dlx
    dlq: docs.uploaded.dlq
